# Generated by Django 2.2 on 2019-08-10 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyVisa',
            fields=[
                ('apply_visa_id', models.AutoField(primary_key=True, serialize=False)),
                ('passport_id', models.CharField(max_length=45)),
                ('visa_status', models.CharField(max_length=45)),
                ('application_requirement', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=45)),
                ('hotel_place', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('visa_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('depart_place', models.CharField(max_length=45)),
                ('destination_place', models.CharField(max_length=45)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='travelmanager.Managers')),
            ],
        ),
        migrations.CreateModel(
            name='Travelers',
            fields=[
                ('traveler_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travelersma', to='travelmanager.ApplyVisa')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='travelmanager.Travelers')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='travelmanager.Trips')),
            ],
        ),
        migrations.CreateModel(
            name='BookHotels',
            fields=[
                ('book_hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_upgrade_status', models.CharField(max_length=45)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BookHotels', to='travelmanager.Hotels')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BookHotels', to='travelmanager.Trips')),
            ],
        ),
        migrations.CreateModel(
            name='BookFlights',
            fields=[
                ('book_flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('depart_place', models.CharField(max_length=45)),
                ('destination_place', models.CharField(max_length=45)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BookFlights', to='travelmanager.Flights')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BookFlights', to='travelmanager.Trips')),
            ],
        ),
        migrations.AddField(
            model_name='applyvisa',
            name='visa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ApplyVisa', to='travelmanager.Visa'),
        ),
    ]
