# Generated by Django 2.2 on 2019-08-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelmanager', '0002_auto_20190810_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='passport_number',
            field=models.CharField(default='', max_length=45),
        ),
    ]
