# Generated by Django 2.2 on 2019-08-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelmanager', '0003_manager_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='telephone_nunber',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
