# Generated by Django 2.2 on 2019-08-10 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travelmanager', '0006_auto_20190810_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyvisa',
            name='visa_apply_number',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='trip',
            name='depart_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='dining_fee',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='trip',
            name='ticket_fee',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_number',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='telephone_nunber',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='telephone_nunber',
            field=models.CharField(default='', max_length=45),
        ),
    ]
