# Generated by Django 2.2 on 2019-08-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelmanager', '0007_auto_20190810_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyvisa',
            name='application_requirement',
        ),
        migrations.RemoveField(
            model_name='applyvisa',
            name='passport_id',
        ),
    ]
