# Generated by Django 2.2 on 2019-08-11 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travelmanager', '0008_auto_20190810_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookflight',
            name='depart_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookflight',
            name='destination_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookflight',
            name='price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='bookhotel',
            name='end_date',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookhotel',
            name='price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='bookhotel',
            name='start_date',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
