# Generated by Django 2.2 on 2019-08-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelmanager', '0012_create_group_permissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manager',
            unique_together={('last_name', 'first_name', 'passport_number')},
        ),
        migrations.AlterUniqueTogether(
            name='traveler',
            unique_together={('last_name', 'first_name', 'passport_number')},
        ),
    ]
